services:
  backend:
    build: .
    image: application-backend:latest
    expose:
      - "${PORT_BACKEND}:${PORT_BACKEND}"
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - rabbitmq

  worker:
    build: .
    image: application-backend:latest
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "${RABBITMQ_ERLANG_COOKIE}"
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    ports:
      - "${RABBITMQ_MI_PORT}:${RABBITMQ_MI_PORT}"
      - "${RABBITMQ_SERVER_PORT}:${RABBITMQ_SERVER_PORT}"
    env_file:
      - .env
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "${PORT_NGINX}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
