# Use the official Nginx base image.
FROM nginx:latest

# Copy your custom nginx.conf into the container.
# Since the context is `nginx/`, you just need to reference the local path to `nginx.conf`
COPY nginx.conf /etc/nginx/nginx.conf

# Set the command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
